# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('western', 'Western'), ('jumpsuits', 'Jumpsuits'), ('traditional', 'TRADITIONAL'), ('ethnic', 'Erhnic'), ('winter-wears', 'Winter-wears'), ('t-shirts', 'T-shirts'), ('kids', 'Kids'), ('casual', 'Casual'), ('formal', 'Formal'), ('denim', 'Denim'), ('sports', 'Sports')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('weddings', 'Weddings'), ('everyday', 'Everyday'), ('outings', 'Outings'), ('gym', 'Gym'), ('interview', 'Interview'), ('party', 'Party'), ('sangeet', 'Sangeet')], max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.Profile'),
        ),
    ]
