# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20181228_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('kids', 'Kids'), ('winter-wears', 'Winter-wears'), ('casual', 'Casual'), ('formal', 'Formal'), ('t-shirts', 'T-shirts'), ('jumpsuits', 'Jumpsuits'), ('denim', 'Denim'), ('sports', 'Sports'), ('ethnic', 'Erhnic'), ('traditional', 'TRADITIONAL'), ('western', 'Western')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('weddings', 'Weddings'), ('outings', 'Outings'), ('party', 'Party'), ('everyday', 'Everyday'), ('gym', 'Gym'), ('interview', 'Interview'), ('sangeet', 'Sangeet')], max_length=9),
        ),
    ]
