# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20181228_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('new', 'New')], default='new', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('traditional', 'TRADITIONAL'), ('formal', 'Formal'), ('casual', 'Casual'), ('ethnic', 'Erhnic'), ('sports', 'Sports'), ('western', 'Western'), ('t-shirts', 'T-shirts'), ('denim', 'Denim'), ('kids', 'Kids'), ('winter-wears', 'Winter-wears'), ('jumpsuits', 'Jumpsuits')], default='traditional', max_length=17),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('weddings', 'Weddings'), ('sangeet', 'Sangeet'), ('party', 'Party'), ('everyday', 'Everyday'), ('interview', 'Interview'), ('gym', 'Gym'), ('outings', 'Outings')], default='party', max_length=9),
        ),
    ]
